[profile.default]
out = 'out'
src = 'src'
libs = ['lib']

# Set the compiler version to match the contracts' requirements
solc = '0.8.20'

# CRITICAL FIX: The remappings are essential for the import path
remapping = [
    'contracts/=lib/contracts/contracts/',
    'forge-std/=lib/forge-std/src/'
]

[rpc_endpoints]
hoodi = "https://rpc.hoodi.ethpandaops.io"
